modLoader="javafml"
loaderVersion="[43,)"
license="0BSD"

[[mods]]
modId="deckcontrols"
version="${file.jarVersion}"
displayName="Steam Deck Native Controls"
authors="NEKOMods team"
displayTest="IGNORE_ALL_VERSION"

description='''
Native Steam Deck controls
'''

[[dependencies.deckcontrols]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deckcontrols]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
